meilisearch:
    url: '%env(MEILISEARCH_URL)%' # URL of the Meilisearch server (mandatory)
    api_key: '%env(MEILISEARCH_API_KEY)%' # API key to access the Meilisearch server (mandatory)
    prefix: '%env(MEILISEARCH_PREFIX)%'
    indices:
        # Define entities or documents that should be indexed to Meilisearch.
        # See https://github.com/meilisearch/meilisearch-symfony/wiki/configure-searchable-data
        - name: imdb_movies
          class: App\Entity\Movie
          enable_serializer_groups: true
          settings:
            filterableAttributes:
              - year
              - type
              - primaryTitle
            sortableAttributes:
              - year
              - type
              - primaryTitle