# ln -s ~/g/survos/survos/packages/api-grid-bundle/assets/src/controllers/sandbox_api_grid_controller.js assets/controllers/sandbox_api_grid_controller.js
when@dev:
  survos_api_grid:
#    stimulus_controller: sandbox_api_grid


